# Generated by Django 4.2.6 on 2024-03-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='details',
            field=models.CharField(default=8, max_length=5000),
            preserve_default=False,
        ),
    ]
